# Dockerfile (multi-stage)
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /workspace

# copiar pom y cachear deps
COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline

# copiar fuentes y compilar
COPY src ./src
RUN mvn -q -DskipTests clean package

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

# copiar JAR ya construido
COPY --from=build /workspace/target/*.jar app.jar

EXPOSE 4002

ENTRYPOINT ["sh","-c","java -jar /app/app.jar"]